services:

  web:
    build: ./docker/web
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/app
      - ./publico:/var/www/html/publico
      - ./scripts:/var/www/html/scripts
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    depends_on:
      - db
      - redis
    networks:
      - weather-net

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weather-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - weather-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge

volumes:
  db_data: