FROM php:8.2-apache

# Instalar dependencias del sistema (incluye libzip-dev para zip, y las necesarias para GD)
RUN apt-get update && apt-get install -y \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) mysqli gd zip \
    && rm -rf /var/lib/apt/lists/*

#Instalar Redis
RUN pecl install redis && docker-php-ext-enable redis

# Habilitar mod_rewrite
RUN a2enmod rewrite

# Cambiar DocumentRoot a publico/
ENV APACHE_DOCUMENT_ROOT /var/www/html/publico
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf

# Permitir .htaccess (Override All)
RUN sed -ri -e 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf